version: 1
build:
  main: cmd/obsidiand
validation: sovereign
accounts:
  - name: alice
    coins:
      - 500000000uobs
      - 200000000stake
  - name: bob
    coins:
      - 100000000uobs
      - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
      - 100000uobs
      - 100000stake
validators:
  - name: alice
    bonded: 100000000stake
